services:
  mongo:
    image: mongo:5.0
    container_name: mongodb-mailoop
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo_data:
